spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/traveldb
    username: root
    password: test1234

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  # swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  profiles:
    active: default
    include:
      - "auth"

  jackson:
    serialization.WRITE_DATES_AS_TIMESTAMPS=false

  output:
    ansi:
      enabled: always

#logging:
#  level:
#    org.hibernate.SQL: debug
